name: frontendTesting
run-name: ${{ github.actor }} is running tests
on:
  push:
    branches:
      - main
      - working-jest-tests-1
jobs:
  run-defined-frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run test
